### ISSUE TITLE
Could you add password option to vnc?

### ISSUE THREAD

**Issue by ghost** [EvanTrow/docker-spotify#1]
Hi,

Would it be possible to add a password option to the vnc connection? How would I do that?

Awaiting your response,

Kind regards,

Johan

**Comment by EvanTrow** [comment]
Hi Johan,

I think this should work: https://github.com/jlesage/docker-baseimage-gui#vnc-password

**Comment by ghost** [comment]
I will try that soon.

Do you know why this happens?

29/09/2022 14:05:47
The VNC desktop is:      142749.fdcservers.net:0
PORT=5900
******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature
yet?
The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:
    x11vnc -ncache 10 ...
One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching
[services.d] starting app...
[app] starting Spotify...
[services.d] done.
terminating with uncaught exception of type boost::wrapexcept<boost::uuids::entropy_error>: getrandom
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping openbox...
[services.d] stopping logmonitor...
[services.d] stopping statusmonitor...
[services.d] stopping nginx...
[services.d] stopping x11vnc...
caught signal: 15
29/09/2022 14:05:50 deleted 40 tile_row polling images.
[services.d] stopping certsmonitor...
[services.d] stopping xvfb...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

My Docker container seems to keep restarting on one of my VPS for testing...

Here is install script that normally works on hetzner VPS, but now I try another provider, but it keeps restarting.

https://github.com/thisisawesome1994/spotify-client-install-docker-ubuntu

**Comment by ghost** [comment]
The only difference I am aware of is the working hetzner VPS does run Ubuntu 22.04, while this one does Ubuntu 20.04

**Comment by ghost** [comment]
I solved both issues.
Had to do a clean 22.04 install.
The original install must have been corrupted somehow.

Thank you for your help

**Comment by EvanTrow** [comment]
Fixed
